#!/usr/bin/bash
clear
mkdir ~/.tcp/
pkg install clang
cd ~/termux-c++
cp tcp $PREFIX/bin
echo "Termux C++ berhasil di-install!"
echo 'Cara pakai: ketik "tcp namaFile.cpp" untuk memulai proses kompilasi'
