#!/usr/bin/bash
clear
file=$1
cp $file ~/.tcp/
cd ~/.tcp
echo "Proses sedang berjalan..."
g++ $file -o ${file%.*}
if [[ -f "${file%.*}" ]]; then
	clear
	./${file%.*}
	rm $file ${1%.*}
else
	rm $file
fi
